server:
  port: 8081

spring:
  application:
    name: personal-finance

  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: test123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: personal-finance
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  env: dev
  jwt:
    issuer: personal-finance
    # dev'de env yoksa da çalışsın (fallback)
    secret: ${APP_JWT_SECRET:dev_secret_key_which_is_more_than_32_characters_long_12345}
    access-token-minutes: 30
    refresh-token-days: 7

  market-rates:
    metals-provider: goldpricez
    goldpricez:
      base-url: "https://goldpricez.com"
      api-key: "9cff6b622de345eca78691a8d969f2a29cff6b62"
      path: "/api/rates/currency/usd/measure/gram/metal/all"
    fx-url-template: "https://api.frankfurter.app/latest?from=%s&to=TRY"
    timeout: 5s

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG
    org.flywaydb.core: DEBUG
    root: INFO
