server:
  port: ${PORT:8081}

spring:
  application:
    name: personal-finance

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  # Prod'da Redis kullanmıyorsan cache kapalı kalsın
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:0}
    cache:
      type: ${CACHE_TYPE:none}

  # Prod'da Kafka yoksa boş bırak
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  env: prod
  jwt:
    issuer: personal-finance
    secret: ${APP_JWT_SECRET}
    access-token-minutes: 30
    refresh-token-days: 7

  market-rates:
    metals-provider: goldpricez
    goldpricez:
      base-url: "https://goldpricez.com"
      api-key: ${GOLDPRICEZ_API_KEY:}
      path: "/api/rates/currency/usd/measure/gram/metal/all"
    fx-url-template: "https://api.frankfurter.app/latest?from=%s&to=TRY"
    timeout: 5s

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.flywaydb: INFO
